version: 2

aliases:
  - &restore-cache
    keys:
      - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - yarn-cache-{{ .Branch }}- # Fallback in case checksum fails

  - &save-cache
    key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

jobs:

  test_and_build:
    docker:
      - image: circleci/node:11
    working_directory: ~/project
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn install
      - save-cache: *save-cache
      - run: CI=false yarn build
      - persist_to_workspace:
          root: build
          paths:
            - '*'

  deploy_preprod:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: build
      - run: sudo pip install awscli
      - run:
          name: Add robots.txt and Deploy to S3
          command: |
            cd build
            echo -e 'User-Agent: *\nDisallow: /' > robots.txt
            export AWS_ACCESS_KEY_ID=${SANDBOX_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${SANDBOX_AWS_SECRET_ACCESS_KEY}
            aws s3 sync . s3://${SANDBOX_S3_BUCKET_NAME}
            aws cloudfront create-invalidation --distribution-id ${SANDBOX_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test_and_build
      - deploy_preprod:
          requires:
            - test_and_build
          filters:
            branches:
              only: master
